fix:  log correctly if session key is not available.
Right now, a missing session key may result in the following stacktrace

```
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_config_diff/compliance/base.py", line 166, in get_devices_with_rendered_configs
    self.check_netbox_secrets()
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_config_diff/compliance/secrets.py", line 94, in check_netbox_secrets
    self.get_master_key()
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_config_diff/compliance/secrets.py", line 39, in get_master_key
    if getattr(self.logger, "log_failure"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'log_failure'
```